// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealEstateListing.Models;

namespace RealEstateListing.Migrations
{
    [DbContext(typeof(RealEstateListingContext))]
    [Migration("20191109044855_SeedBooks")]
    partial class SeedBooks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RealEstateListing.Models.RealEstate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<int>("NoOfRooms")
                        .HasColumnType("int");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RealEstate");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 300000.0,
                            NoOfRooms = 3,
                            Sqft = 2100,
                            Type = "Apartment"
                        },
                        new
                        {
                            Id = 2,
                            Cost = 170000.0,
                            NoOfRooms = 3,
                            Sqft = 1350,
                            Type = "Condominium"
                        },
                        new
                        {
                            Id = 3,
                            Cost = 210000.0,
                            NoOfRooms = 4,
                            Sqft = 1780,
                            Type = "Co-op"
                        },
                        new
                        {
                            Id = 4,
                            Cost = 231000.0,
                            NoOfRooms = 3,
                            Sqft = 2100,
                            Type = "Single family"
                        },
                        new
                        {
                            Id = 5,
                            Cost = 450000.0,
                            NoOfRooms = 5,
                            Sqft = 3000,
                            Type = "Apartment"
                        },
                        new
                        {
                            Id = 6,
                            Cost = 185000.0,
                            NoOfRooms = 3,
                            Sqft = 2050,
                            Type = "Single family"
                        },
                        new
                        {
                            Id = 7,
                            Cost = 215200.0,
                            NoOfRooms = 4,
                            Sqft = 2300,
                            Type = "Condominium"
                        },
                        new
                        {
                            Id = 8,
                            Cost = 150000.0,
                            NoOfRooms = 2,
                            Sqft = 1500,
                            Type = "Single family"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
